name: 'nathan_analytics'
version: '1.0.0'
config-version: 2

profile: 'nathan_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nathan_analytics:

    # Persist descriptions into BigQuery metadata
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']

    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate']

    marts:
      +schema: production
      +tags: ['marts']

      dimensions:
        +materialized: table
        +tags: ['dimensions']

      facts:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: customer_id
        +on_schema_change: sync_all_columns
        +tags: ['facts']

seeds:
  nathan_analytics:
    +schema: seeds
    +quote_columns: false

snapshots:
  nathan_analytics:
    +target_schema: snapshots

vars:
  start_date: '2020-01-01'